[package]
name = "lavaan-kernels"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ndarray = "0.16.1"

[lib]
name = "lavaan_kernels"
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "lav_matrix"
path = "src/bin/lav_matrix.rs"

[[bench]]
name = "lav_matrix"
path = "benches/lav_matrix.rs"
harness = false

[[bench]]
name = "lav_model_gradient"
path = "benches/lav_model_gradient.rs"
harness = false

[[bench]]
name = "lav_model_vcov"
path = "benches/lav_model_vcov.rs"
harness = false

[[bench]]
name = "lav_model_estimate"
path = "benches/lav_model_estimate.rs"
harness = false

[[bench]]
name = "lav_model_objective"
path = "benches/lav_model_objective.rs"
harness = false

[[test]]
name = "lav_model_gradient"
path = "../tests/lav_model_gradient.rs"

[[test]]
name = "lav_model_vcov"
path = "../tests/lav_model_vcov.rs"

[[test]]
name = "lav_model_estimate"
path = "../tests/lav_model_estimate.rs"

[[test]]
name = "lav_model_objective"
path = "../tests/lav_model_objective.rs"
