# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib lavaan, .registration = TRUE
NULL

#' Returns whether the package-native Rust backend is loaded.
#' @export
lav_rust_backend_ping <- function() .Call(wrap__lav_rust_backend_ping)

#' Build an immutable continuous-LISREL model plan. The returned external
#' pointer owns copied numeric state and is finalized by R when its optimizer
#' cache is released.
#' @export
lav_rust_lisrel_ml_plan_new <- function(sample_cov, sample_mean, nvar, nfac, beta_present, nobs, ntotal, free_group, free_kind, free_element, free_parameter, nfree, meanstructure) .Call(wrap__lav_rust_lisrel_ml_plan_new, sample_cov, sample_mean, nvar, nfac, beta_present, nobs, ntotal, free_group, free_kind, free_element, free_parameter, nfree, meanstructure)

#' Standard ML numerical objective used by `lav_model_objective.R`.
#' @export
lav_rust_model_objective_ml <- function(`_sigma_hat`, sigma_hat_inv, data_cov, mu_hat, data_mean, sigma_hat_log_det, data_cov_log_det, meanstructure) .Call(wrap__lav_rust_model_objective_ml, `_sigma_hat`, sigma_hat_inv, data_cov, mu_hat, data_mean, sigma_hat_log_det, data_cov_log_det, meanstructure)

#' Combined standard-ML objective and delta-method gradient for all groups.
#'
#' `R/lav_model_objective_gradient.R` prepares the packed numerical state and
#' owns the model/S4 orchestration. The returned vector is
#' `[objective, group_objectives..., gradient...]`.
#' @export
lav_rust_model_objective_gradient_ml <- function(sigma, sigma_inv, data_cov, mu_hat, data_mean, sigma_log_det, data_cov_log_det, delta, nvar, delta_rows, delta_cols, group_weights, meanstructure) .Call(wrap__lav_rust_model_objective_gradient_ml, sigma, sigma_inv, data_cov, mu_hat, data_mean, sigma_log_det, data_cov_log_det, delta, nvar, delta_rows, delta_cols, group_weights, meanstructure)

#' Fully numerical continuous-LISREL ML objective and gradient.
#'
#' R only marshals model matrices, free-element maps, and sample moments. Rust
#' computes implied moments, Cholesky metadata, objective, and gradient.
#' @export
lav_rust_model_objective_gradient_lisrel_ml <- function(lambda, theta, psi, beta, nu, alpha, sample_cov, sample_mean, nvar, nfac, beta_present, nobs, ntotal, free_group, free_kind, free_element, free_parameter, nfree, meanstructure) .Call(wrap__lav_rust_model_objective_gradient_lisrel_ml, lambda, theta, psi, beta, nu, alpha, sample_cov, sample_mean, nvar, nfac, beta_present, nobs, ntotal, free_group, free_kind, free_element, free_parameter, nfree, meanstructure)

#' Evaluate the fully numerical continuous-LISREL ML objective and gradient
#' using immutable state owned by `LisrelMlPlan`.
#' @export
lav_rust_model_objective_gradient_lisrel_ml_with_plan <- function(plan, lambda, theta, psi, beta, nu, alpha) .Call(wrap__lav_rust_model_objective_gradient_lisrel_ml_with_plan, plan, lambda, theta, psi, beta, nu, alpha)

#' Opt-in timing for the fully numerical continuous-LISREL ML objective and
#' gradient. The first result values are identical to
#' `lav_rust_model_objective_gradient_lisrel_ml`; the final six values are
#' bridge conversion, plan/free-map, implied-moment, factorization/objective,
#' direct-score, and result-buffer milliseconds respectively.
#' @export
lav_rust_model_objective_gradient_lisrel_ml_diagnostics <- function(lambda, theta, psi, beta, nu, alpha, sample_cov, sample_mean, nvar, nfac, beta_present, nobs, ntotal, free_group, free_kind, free_element, free_parameter, nfree, meanstructure) .Call(wrap__lav_rust_model_objective_gradient_lisrel_ml_diagnostics, lambda, theta, psi, beta, nu, alpha, sample_cov, sample_mean, nvar, nfac, beta_present, nobs, ntotal, free_group, free_kind, free_element, free_parameter, nfree, meanstructure)

#' Flattened diagonal FIML starting moments for baseline independence models.
#' @export
lav_rust_baseline_fiml_moments <- function(pattern_lengths, observed_indices, frequencies, means, sy_diagonals, nvar) .Call(wrap__lav_rust_baseline_fiml_moments, pattern_lengths, observed_indices, frequencies, means, sy_diagonals, nvar)

#' Diagonal FIML normal log likelihood for baseline independence models.
#' @export
lav_rust_baseline_fiml_loglik <- function(pattern_lengths, observed_indices, frequencies, means, sy_diagonals, mean, var) .Call(wrap__lav_rust_baseline_fiml_loglik, pattern_lengths, observed_indices, frequencies, means, sy_diagonals, mean, var)

# nolint end
