# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib lavaan, .registration = TRUE
NULL

lav_rust_backend_ping <- function() .Call(wrap__lav_rust_backend_ping)

lav_rust_matrix_vec <- function(input) .Call(wrap__lav_rust_matrix_vec, input)

lav_rust_matrix_vecr <- function(input) .Call(wrap__lav_rust_matrix_vecr, input)

lav_rust_matrix_diag_prepost <- function(input, d) .Call(wrap__lav_rust_matrix_diag_prepost, input, d)

lav_rust_matrix_delta_a_delta <- function(delta, a1) .Call(wrap__lav_rust_matrix_delta_a_delta, delta, a1)

lav_rust_model_objective_ml <- function(sigma_hat, sigma_hat_inv, data_cov, mu_hat, data_mean, sigma_hat_log_det, data_cov_log_det, meanstructure) .Call(wrap__lav_rust_model_objective_ml, sigma_hat, sigma_hat_inv, data_cov, mu_hat, data_mean, sigma_hat_log_det, data_cov_log_det, meanstructure)

lav_rust_model_objective_ml_res <- function(sigma_hat, sigma_hat_inv, res_cov, res_int, res_slopes, mu_hat, pi0, cov_x, mean_x, sigma_hat_log_det, res_cov_log_det) .Call(wrap__lav_rust_model_objective_ml_res, sigma_hat, sigma_hat_inv, res_cov, res_int, res_slopes, mu_hat, pi0, cov_x, mean_x, sigma_hat_log_det, res_cov_log_det)

lav_rust_model_objective_gls <- function(sigma_hat, data_cov, data_cov_inv, mu_hat, data_mean, meanstructure, correlation) .Call(wrap__lav_rust_model_objective_gls, sigma_hat, data_cov, data_cov_inv, mu_hat, data_mean, meanstructure, correlation)

lav_rust_model_objective_wls <- function(wls_est, wls_obs, wls_v) .Call(wrap__lav_rust_model_objective_wls, wls_est, wls_obs, wls_v)

lav_rust_model_objective_dwls <- function(wls_est, wls_obs, wls_vd) .Call(wrap__lav_rust_model_objective_dwls, wls_est, wls_obs, wls_vd)

lav_rust_model_vcov_delta_a_delta <- function(delta, a1) .Call(wrap__lav_rust_model_vcov_delta_a_delta, delta, a1)

lav_rust_model_vcov_sandwich <- function(left, middle) .Call(wrap__lav_rust_model_vcov_sandwich, left, middle)

lav_rust_model_vcov_jacobian_vcov_jacobian_t <- function(jac, vcov) .Call(wrap__lav_rust_model_vcov_jacobian_vcov_jacobian_t, jac, vcov)

lav_rust_matrix_diagh_idx <- function(n) .Call(wrap__lav_rust_matrix_diagh_idx, n)

lav_rust_matrix_antidiag_idx <- function(n) .Call(wrap__lav_rust_matrix_antidiag_idx, n)

lav_rust_matrix_diag_idx <- function(n) .Call(wrap__lav_rust_matrix_diag_idx, n)

lav_rust_matrix_vech_idx <- function(n, diagonal) .Call(wrap__lav_rust_matrix_vech_idx, n, diagonal)

lav_rust_matrix_vech_row_idx <- function(n, diagonal) .Call(wrap__lav_rust_matrix_vech_row_idx, n, diagonal)

lav_rust_matrix_vech_col_idx <- function(n, diagonal) .Call(wrap__lav_rust_matrix_vech_col_idx, n, diagonal)

lav_rust_matrix_vechr_idx <- function(n, diagonal) .Call(wrap__lav_rust_matrix_vechr_idx, n, diagonal)

lav_rust_matrix_vechu_idx <- function(n, diagonal) .Call(wrap__lav_rust_matrix_vechu_idx, n, diagonal)

lav_rust_matrix_vechru_idx <- function(n, diagonal) .Call(wrap__lav_rust_matrix_vechru_idx, n, diagonal)

lav_rust_matrix_vech <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vech, input, diagonal)

lav_rust_matrix_vechr <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vechr, input, diagonal)

lav_rust_matrix_vechu <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vechu, input, diagonal)

lav_rust_matrix_vechru <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vechru, input, diagonal)

lav_rust_matrix_vech_reverse <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vech_reverse, input, diagonal)

lav_rust_matrix_vechru_reverse <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vechru_reverse, input, diagonal)

lav_rust_matrix_upper2full <- function(input, diagonal) .Call(wrap__lav_rust_matrix_upper2full, input, diagonal)

lav_rust_matrix_vechr_reverse <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vechr_reverse, input, diagonal)

lav_rust_matrix_vechu_reverse <- function(input, diagonal) .Call(wrap__lav_rust_matrix_vechu_reverse, input, diagonal)

lav_rust_matrix_lower2full <- function(input, diagonal) .Call(wrap__lav_rust_matrix_lower2full, input, diagonal)

lav_rust_model_gradient_conditional_x_sample_cache <- function(mean_x, cov_x, res_int, res_slopes) .Call(wrap__lav_rust_model_gradient_conditional_x_sample_cache, mean_x, cov_x, res_int, res_slopes)

lav_rust_model_gradient_omega_ml <- function(sigma, sigma_inv, sample_cov, mean_diff, meanstructure) .Call(wrap__lav_rust_model_gradient_omega_ml, sigma, sigma_inv, sample_cov, mean_diff, meanstructure)

lav_rust_model_gradient_omega_gls <- function(sigma, weight_inv, sample_cov, mean_diff, meanstructure, nobs) .Call(wrap__lav_rust_model_gradient_omega_gls, sigma, weight_inv, sample_cov, mean_diff, meanstructure, nobs)

lav_rust_model_gradient_omega_missing_pattern <- function(sigma_inv, sample_cov, mean_diff, var_idx, nvar, weight) .Call(wrap__lav_rust_model_gradient_omega_missing_pattern, sigma_inv, sample_cov, mean_diff, var_idx, nvar, weight)

lav_rust_model_gradient_delta_post <- function(delta, post, scale) .Call(wrap__lav_rust_model_gradient_delta_post, delta, post, scale)

lav_rust_model_gradient_t_d1_delta <- function(d1, delta, scale) .Call(wrap__lav_rust_model_gradient_t_d1_delta, d1, delta, scale)

lav_rust_model_gradient_group_weight <- function(log_group_weight, observed_group_weight, total_nobs) .Call(wrap__lav_rust_model_gradient_group_weight, log_group_weight, observed_group_weight, total_nobs)

lav_rust_model_gradient_wls <- function(delta, wls_v, diff, group_weight) .Call(wrap__lav_rust_model_gradient_wls, delta, wls_v, diff, group_weight)

lav_rust_model_gradient_dwls <- function(delta, wls_vd, diff, group_weight) .Call(wrap__lav_rust_model_gradient_dwls, delta, wls_vd, diff, group_weight)

lav_rust_model_gradient_ml_conditional_post <- function(c3, obs, mu, pi, sigma_inv, res_cov) .Call(wrap__lav_rust_model_gradient_ml_conditional_post, c3, obs, mu, pi, sigma_inv, res_cov)

lav_rust_model_gradient_ml_conditional <- function(delta, post, group_weight) .Call(wrap__lav_rust_model_gradient_ml_conditional, delta, post, group_weight)

lav_rust_model_gradient_ml_group <- function(delta, omega, omega_mu, group_weight, meanstructure, group_weight_free) .Call(wrap__lav_rust_model_gradient_ml_group, delta, omega, omega_mu, group_weight, meanstructure, group_weight_free)

lav_rust_model_gradient_ntrls_post <- function(sample_cov, model_cov, sigma_inv, mean_observed, mean_model, meanstructure) .Call(wrap__lav_rust_model_gradient_ntrls_post, sample_cov, model_cov, sigma_inv, mean_observed, mean_model, meanstructure)

lav_rust_model_estimate_pack <- function(values, k0, k) .Call(wrap__lav_rust_model_estimate_pack, values, k0, k)

lav_rust_model_estimate_unpack_unscale <- function(values, k0, k, parscale) .Call(wrap__lav_rust_model_estimate_unpack_unscale, values, k0, k, parscale)

lav_rust_model_estimate_gradient_postprocess <- function(dx, parscale, k, total_nobs, pml) .Call(wrap__lav_rust_model_estimate_gradient_postprocess, dx, parscale, k, total_nobs, pml)

# nolint end
